export enum SWFTags {
    Unknown = -1,
    End,
    ShowFrame,
    DefineShape,
    FreeCharacter,
    PlaceObject,
    RemoveObject,
    DefineBits,
    DefineButton,
    JPEGTables,
    SetBackgroundColor,
    DefineFont,
    DefineText,
    DoAction,
    DefineFontInfo,
    DefineSound,
    StartSound,
    /**
     * @deprecated StopSoundTag has no structure, and StartSound offers the functionality of stopping sound.  Use SWFTags.StartSound instead.
     */
    StopSound,
    DefineButtonSound,
    SoundStreamHead,
    SoundStreamBlock,
    DefineBitsLossless,
    DefineBitsJPEG2,
    DefineShape2,
    DefineButtonCxform,
    Protect,
    PathsArePostscript,
    PlaceObject2,
    RemoveObject2 = 28,
    SyncFrame,
    FreeAll = 31,
    DefineShape3,
    DefineText2,
    DefineButton2,
    DefineBitsJPEG3,
    DefineBitsLossless2,
    DefineEditText,
    DefineVideo,
    DefineSprite,
    NameCharacter,
    ProductInfo,
    DefineTextFormat,
    FrameLabel,
    SoundStreamHead2 = 45,
    DefineMorphShape,
    GenerateFrame,
    DefineFont2,
    GeneratorCommand,
    DefineCommandObject,
    CharacterSet,
    ExternalFont,
    Export = 56,
    Import,
    EnableDebugger,
    DoInitAction,
    DefineVideoStream,
    VideoFrame,
    DefineFontInfo2,
    DebugID,
    EnableDebugger2,
    ScriptLimits,
    SetTabIndex,
    FileAttributes = 69,
    PlaceObject3,
    Import2,
    DoABCDefine,
    DefineFontAlignZones,
    CSMTextSettings,
    DefineFont3,
    SymbolClass,
    Metadata,
    DefineScalingGrid,
    DoABC = 82,
    DefineShape4,
    DefineMorphShape2,
    DefineSceneAndFrameLabelData = 86,
    DefineBinaryData,
    DefineFontName,
    DefineBitsJPEG4 = 90
}

export default SWFTags